# -*- coding: utf-8 -*-
"""ialabelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zb93HEnyZzKTFHkRmAzY5G0TrB3PdI5j
"""

# 0. Instalar zstd (¡La pieza que faltaba en Colab!)
!apt-get update && apt-get install -y zstd

# 1. Instalar la librería de Python
!pip install ollama pandas

# 2. Instalar el motor de Ollama en Linux (el sistema de Colab)
!curl -fsSL https://ollama.com/install.sh | sh

# 3. Iniciar el servidor de Ollama en segundo plano
import subprocess
import time
print("Iniciando el servidor de Ollama...")
subprocess.Popen(["ollama", "serve"])
time.sleep(5)

# 4. Descargar el modelo
print("Descargando el modelo...")
!ollama pull qwen2.5:14b
print("¡Ollama listo y modelo descargado!")

# -*- coding: utf-8 -*-
"""
ialabelling.py — Extractor de relaciones familiares con evaluación automática.
Configurado para Qwen2.5-14B en Local vía Ollama.
"""

import os
import re
import time
import pandas as pd
import ollama

PROVEEDOR = "ollama"
MODELO = "qwen2.5:14b"

CSV_ENTRADA  = "family_relations_noisy_1000_EN.csv"
CSV_SALIDA   = "resultados_evaluacion_qwen.csv"
# -----------------------------------------------------------------------------

PROMPT_SISTEMA = """You are a strict data extraction algorithm. You DO NOT converse.
Extract family relationships and birthdates from the text using exactly this format: Entity1 ---> [LABEL] ---> Entity2

ALLOWED LABELS: [SPOUSE], [CHILD], [PARENT], [SIBLING], [BIRTHDATE].

CRITICAL DIRECTION RULES:
- [CHILD] means "Entity1 has a child named Entity2". Format: ParentName ---> [CHILD] ---> ChildName
- [PARENT] means "Entity1 has a parent named Entity2". Format: ChildName ---> [PARENT] ---> ParentName
- Bidirectional constraints: [SPOUSE] and [SIBLING] must ALWAYS be output in both directions on separate lines (A to B, B to A).
- Both Parents: If two people share or adopt a child, map the child to BOTH parents separately.
- Do NOT assume marriage just because two people adopt or have a child together. Only use [SPOUSE] if explicitly stated (married, hitched).
- [BIRTHDATE]: ONLY extract if a specific numerical date (e.g., DD/MM/YYYY) is given. NEVER extract relative words like "yesterday", "today", or leave it blank.
- EXTRACT [BIRTHDATE] for EVERY child mentioned with an explicit numerical date, regardless of other irrelevant details. DO NOT skip this label.

EXAMPLES:

Text: Christopher Edward Nolan (Londres, 30 de julio de 1970) and his brother Jonathan Nolan wrote the script.
Output:
Christopher Edward Nolan ---> [BIRTHDATE] ---> 30/07/1970
Christopher Edward Nolan ---> [SIBLING] ---> Jonathan Nolan
Jonathan Nolan ---> [SIBLING] ---> Christopher Edward Nolan

Text: PersonA was born on 15/04/1985. They are married to PersonB. Their child PersonC was born on 20/11/2010.
Output:
PersonA ---> [BIRTHDATE] ---> 15/04/1985
PersonA ---> [SPOUSE] ---> PersonB
PersonB ---> [SPOUSE] ---> PersonA
PersonA ---> [CHILD] ---> PersonC
PersonB ---> [CHILD] ---> PersonC
PersonC ---> [PARENT] ---> PersonA
PersonC ---> [PARENT] ---> PersonB
PersonC ---> [BIRTHDATE] ---> 20/11/2010

Text: PersonX and PersonY adopted PersonZ.
Output:
PersonX ---> [CHILD] ---> PersonZ
PersonY ---> [CHILD] ---> PersonZ
PersonZ ---> [PARENT] ---> PersonX
PersonZ ---> [PARENT] ---> PersonY

Text: PersonA is the child of PersonB and PersonC.
Output:
PersonB ---> [CHILD] ---> PersonA
PersonC ---> [CHILD] ---> PersonA
PersonA ---> [PARENT] ---> PersonB
PersonA ---> [PARENT] ---> PersonC

Text: PersonQ is hitched to PersonW. Their kid PersonE had a bday yesterday.
Output:
PersonQ ---> [SPOUSE] ---> PersonW
PersonW ---> [SPOUSE] ---> PersonQ
PersonQ ---> [CHILD] ---> PersonE
PersonW ---> [CHILD] ---> PersonE
PersonE ---> [PARENT] ---> PersonQ
PersonE ---> [PARENT] ---> PersonW

Text: PersonA visited PersonB. No kinship was indicated.
Output:
NONE
"""

def normalizar_linea(linea: str) -> str:
    """
    Limpia una línea de salida del modelo para que sea comparable con el gold standard.
    """
    linea = linea.split('(')[0].strip()
    linea = linea.replace('`', '').strip()
    linea = re.sub(r'\s*--->\s*', ' ---> ', linea).strip()

    # --- ESCUDO ANTI-YESTERDAY ---
    # Si la IA intenta extraer un cumpleaños, validamos que al menos tenga un número.
    # Si es "yesterday" o un espacio en blanco, Python elimina la línea.
    if "[BIRTHDATE]" in linea and not any(char.isdigit() for char in linea):
        return ""

    # Agrega una excepción para no omitir fechas por otros números.
    if "[BIRTHDATE]" in linea:
        # Extraer fecha algo como DD/MM/AAAA tenga otros números
        fecha_match = re.search(r'\d{2}/\d{2}/\d{4}', linea)
        linea = fecha_match.group(0) if fecha_match else ""

    return linea

def es_respuesta_vacia(texto: str) -> bool:
    return bool(re.match(r'^none\b', texto.strip(), re.IGNORECASE))

def parsear_salida(salida_ia: str) -> set[str]:
    """Elimina los bloques de razonamiento <think> y extrae las relaciones."""
    # Pulverizamos el bloque de razonamiento de Qwen si decide usarlo
    salida_ia = re.sub(r'<think>.*?</think>', '', salida_ia, flags=re.DOTALL).strip()

    if es_respuesta_vacia(salida_ia):
        return set()

    lineas = []
    for linea in salida_ia.split('\n'):
        if '--->' in linea:
            linea_limpia = normalizar_linea(linea)
            if linea_limpia:
                lineas.append(linea_limpia)
    return set(lineas)

def llamar_api_ollama(texto: str, modelo: str) -> str:
    """Llama al servidor local de Ollama."""
    prompt_usuario = f"Text: {texto}\nOutput:"
    prompt_completo = f"{PROMPT_SISTEMA}\n\n{prompt_usuario}"

    try:
        respuesta = ollama.generate(
            model=modelo,
            prompt=prompt_completo,
            options={"temperature": 0.0, "num_predict": 512},
        )
        return respuesta["response"].strip()
    except Exception as e:
        return f"Error: {str(e)}"

def evaluar_dataset(ruta_csv: str, modelo: str):
    print(f"Cargando dataset desde '{ruta_csv}'...")
    try:
        df = pd.read_csv(ruta_csv)
    except FileNotFoundError:
        print(f"[!] Error: No se encontró el archivo '{ruta_csv}'.")
        return

    df["expected_output"] = df["expected_output"].fillna("")
    total_casos = len(df)

    casos_ya_procesados: set = set()
    columnas_resultado = ["id", "input", "expected_output", "salida_ia", "acierto"]

    if os.path.exists(CSV_SALIDA):
        df_previo = pd.read_csv(CSV_SALIDA)
        casos_ya_procesados = set(df_previo["id"].astype(str))
        print(f"  ↩ Reanudando: {len(casos_ya_procesados)} casos ya procesados.")
    else:
        pd.DataFrame(columns=columnas_resultado).to_csv(CSV_SALIDA, index=False)

    aciertos  = 0
    errores   = []
    procesados_esta_sesion = 0
    tiempo_inicio = time.time()

    print("=" * 60)
    print(f" INICIANDO EVALUACIÓN EN LOCAL | Modelo: {modelo}")
    print("=" * 60)

    for index, row in df.iterrows():
        id_caso        = str(row["id"])
        texto_input    = row["input"]
        salida_esperada = str(row["expected_output"]).strip()

        if id_caso in casos_ya_procesados:
            continue

        salida_cruda = llamar_api_ollama(texto_input, modelo)

        set_esperado = set(l.strip() for l in salida_esperada.split('\n') if l.strip())
        set_ia = parsear_salida(salida_cruda)
        es_acierto = (set_ia == set_esperado)

        if es_acierto:
            aciertos += 1
            print(f"[{index + 1}/{total_casos}] Caso {id_caso}: ✅ ACIERTO")
        else:
            errores.append(id_caso)
            print(f"[{index + 1}/{total_casos}] Caso {id_caso}: ❌ ERROR")
            print(f"   Texto:       {texto_input}")
            print(f"   Esperado:    {set_esperado}")
            print(f"   IA devolvió: {set_ia}")
            print("-" * 60)

        fila_resultado = pd.DataFrame([{
            "id":              id_caso,
            "input":           texto_input,
            "expected_output": salida_esperada,
            "salida_ia":       salida_cruda,
            "acierto":         es_acierto,
        }])
        fila_resultado.to_csv(CSV_SALIDA, mode="a", header=False, index=False)

        procesados_esta_sesion += 1

        # Estimación de tiempo
        tiempo_transcurrido = time.time() - tiempo_inicio
        seg_por_caso = tiempo_transcurrido / procesados_esta_sesion
        casos_restantes = total_casos - (index + 1)
        eta_min = (seg_por_caso * casos_restantes) / 60
        print(f"   ⏱ Tiempo restante estimado: {eta_min:.1f} min")

    # REPORTE FINAL
    df_total = pd.read_csv(CSV_SALIDA)
    total_procesados = len(df_total)
    total_aciertos   = df_total["acierto"].sum()
    accuracy = (total_aciertos / total_procesados * 100) if total_procesados > 0 else 0

    print("\n" + "=" * 50)
    print("      REPORTE FINAL DE EVALUACIÓN (QWEN 14B LOCAL)")
    print("=" * 50)
    print(f"Casos procesados: {total_procesados} / {total_casos}")
    print(f"Aciertos:         {int(total_aciertos)}")
    print(f"Errores:          {total_procesados - int(total_aciertos)}")
    print(f"ACCURACY:         {accuracy:.2f}%")
    print("=" * 50)

if __name__ == "__main__":
    evaluar_dataset(CSV_ENTRADA, MODELO)